update code for debug in CI/CD

diff --git a/.github/workflows/runTest.yml b/.github/workflows/runTest.yml
--- a/.github/workflows/runTest.yml
+++ b/.github/workflows/runTest.yml
@@ -26,8 +26,20 @@ jobs:
     - name: install YACHT locally
       run: pip install -e .
 
-    - name: Verify compilation output
-      run: ls -l src/yacht
+    - name: Verify installation of run_yacht_train_core in site-packages
+      run: |
+        SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
+        if [ -f "$SITE_PACKAGES/yacht/run_yacht_train_core" ]; then
+          echo "run_yacht_train_core found in site-packages."
+        else
+          echo "run_yacht_train_core not found in site-packages."
+          exit 1
+        fi
+
+    - name: List contents of site-packages
+      run: |
+        SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
+        ls -R $SITE_PACKAGES
 
     - name: make training data
       run: yacht train --ref_file './tests/testdata/20_genomes_sketches.zip' --ksize 31 --prefix 'gtdb_ani_thresh_0.95' --ani_thresh 0.95 --outdir ./ --force
